### ISSUE TITLE
Cannot connect to mobile mouse lite on android

### ISSUE THREAD

**Issue by uszasty** [anoved/mmserver#37]
When I try to connect my phone to server, that happening every second:
mmserver[13489]: [192.168.1.18] session ended
mmserver[13489]: [192.168.1.18] connected
mmserver[13489]: [192.168.1.18] disconnected (read failed: Resource temporarily unavailable)
And android app is freezing with searching/connecting screen.

**Comment by anoved** [comment]
Thanks for reporting this (and sorry for the delayed reply).

This looks like the same problem discussed in thread #36. Unfortunately I do not have the means to test mmserver with the Android version of Mobile Mouse, so my ability to resolve this myself is limited. Evidently something about the Android version's connection sequence now differs from the iOS version.

It would help to know if you have been able to connect to mmserver with a _previous_ version of the Android Mobile Mouse app. That would clarify whether the bug is due to something that has changed in the latest version of the Android app.

**Comment by anoved** [comment]
Merging with issue #36
